#!/bin/bash
#
# Shell snoopy process simulator
# Copyright (C) 2016  Victor C. Salas P. (aka nmag) <nmagko@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or (at
#  your option) any later version.
#
#  This program is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#

if [ "$1" == "" ]; then
    heavy_p="snoopy"
else
    heavy_p=$1
fi

if [ "$2" == "" ] || [ "$2" -gt 0 ]; then
    time_s=20
else
    time_s=$2
fi

echo "Simulate $heavy_p process..."
sleep $time_s
echo "End of process."
echo "Ok"

exit 0
